### ISSUE TITLE
Aura not syncing with CUE or CorsairLink4

### ISSUE THREAD

**Issue by DMCK96** [CyanLabs/RGBSync#1]
When running RGB Sync as admin, Aura lights go off untill I go back into aura to change the colour for example. 1 of my cue devices (MM800 Polaris) goes solid white, and another (VOID Wireless headset) doesn't change at all. My Corsair Vengeance RGB also do not change at all.

Running Windows10, latest version of all software and drivers.

The only SDK library I can find not included in your software is cpuidsdk.dll and cpuidsdk64.dll in CorsairLink4.

**Comment by Fma965** [comment]
How many lighting zones does your mottherboard have?

**Comment by DMCK96** [comment]
My motherboard has 2 RGB Headers and lighting on the PCH heatsink. 

Asus Strix b350-f

**Comment by Fma965** [comment]
How many lighting zones are on pch


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: DMCK96 <notifications@github.com> Date: 11/12/2017  12:28  (GMT+00:00) To: CyanLabs/RGBSync <RGBSync@noreply.github.com> Cc: Scott <fma96580@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [CyanLabs/RGBSync] Aura not syncing with CUE or CorsairLink4 (#1) 
My motherboard has 2 RGB Headers and lighting on the PCH heatsink.
Asus Strix b350-f

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CyanLabs/RGBSync","title":"CyanLabs/RGBSync","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CyanLabs/RGBSync"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DMCK96 in #1: My motherboard has 2 RGB Headers and lighting on the PCH heatsink. \r\n\r\nAsus Strix b350-f"}],"action":{"name":"View Issue","url":"https://github.com/CyanLabs/RGBSync/issues/1#issuecomment-350710660"}}}

**Comment by DMCK96** [comment]
Just the one.

![image](https://user-images.githubusercontent.com/26749858/33831694-f890a642-de70-11e7-8e5d-f763e77f176a.png)

**Comment by DMCK96** [comment]
If it's of any use, even though RGB Vengeance are certified as compatible with Aura, they do not sync and this is a known issue for numerous months. One of the main reasons I looked at RGBSync as an alternative.

**Comment by Fma965** [comment]
That looks like more than 1 led in that... in aura how many zones are listed when setting a static colour.
Memory and other aura sync compatible devices are not accessible from the sdk therefore not supported in rgb.net and therefore not supported in rgbsync
Also what version of rgbsync are you running.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: DMCK96 <notifications@github.com> Date: 11/12/2017  12:45  (GMT+00:00) To: CyanLabs/RGBSync <RGBSync@noreply.github.com> Cc: Scott <fma96580@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [CyanLabs/RGBSync] Aura not syncing with CUE or CorsairLink4 (#1) 
If it's of any use, even though RGB Vengeance are certified as compatible with Aura, they do not sync and this is a known issue for numerous months. One of the main reasons I looked at RGBSync as an alternative.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CyanLabs/RGBSync","title":"CyanLabs/RGBSync","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CyanLabs/RGBSync"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DMCK96 in #1: If it's of any use, even though RGB Vengeance are certified as compatible with Aura, they do not sync and this is a known issue for numerous months. One of the main reasons I looked at RGBSync as an alternative."}],"action":{"name":"View Issue","url":"https://github.com/CyanLabs/RGBSync/issues/1#issuecomment-350714339"}}}

**Comment by DMCK96** [comment]
Apologies I just found all the zones.
PCH-1 to 4
RGB Strip 1 (both RGB Headers count as 1 zone).

RGBSync V1.02

**Comment by Fma965** [comment]
Since this is very early in development i'm not really able to help further at this time. there are hundreds of issues with this software and i don't currently have the time to resolve these.

All i can suggest is running it from the source via visual studio and seeing if any errors show. also make sure you uncheck the boxes for devices you don't have, the icon appears in the notification area (system tray)

**Comment by Fma965** [comment]
Hi @DMCK96 please try the new release.

https://github.com/CyanLabs/RGBSync/releases/tag/1.1.0

Thanks.

**Comment by DMCK96** [comment]
On startup it disables my Aura RGB lights and Corsair CUE lights (Corsair LINK are still on).

After saving settings (only CUE and Link selected) I receive a JIT exception, can no longer start the application without this JIT error appearing.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no elements
   at RGBSync.Settings.Form1_Load(Object sender, EventArgs e) in C:\Users\scott.CYANLABS\source\repos\RGBSync\Settings.cs:line 62
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RGBSync
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGBSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2600.0 built by: NET471REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
RGB.NET.Core
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Core.DLL
----------------------------------------
RGB.NET.Devices.Asus
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Asus.DLL
----------------------------------------
RGB.NET.Groups
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Groups.DLL
----------------------------------------
RGB.NET.Devices.Msi
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Msi.DLL
----------------------------------------
RGB.NET.Devices.CorsairLink
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.CorsairLink.DLL
----------------------------------------
RGB.NET.Devices.Novation
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Novation.DLL
----------------------------------------
RGB.NET.Devices.CoolerMaster
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.CoolerMaster.DLL
----------------------------------------
RGB.NET.Devices.Logitech
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Logitech.DLL
----------------------------------------
RGB.NET.Devices.Corsair
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Corsair.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.2.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/System.ValueTuple.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
HidSharp
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/HidSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by Fma965** [comment]
@DMCK96 do you have discord? add Fma965#2743

is aura running?
